import {
  Document, Packer, Paragraph, TextRun, HeadingLevel,
  AlignmentType, Table, TableRow, TableCell, WidthType,
  BorderStyle, PageBreak, ShadingType,
} from 'docx';
import { writeFile } from 'fs/promises';
import { formatTokens, formatCost, formatDuration, formatDate } from '../utils/format.js';

/**
 * Export stitched sessions to a DOCX file.
 * Structured for AI readability with clear headings, turn numbering, timestamps.
 */
export async function exportDocx(outputPath, projectName, sessions, analytics, options = {}) {
  const children = [];

  // ── Cover Page ─────────────────────────────────────────────
  children.push(
    new Paragraph({ spacing: { before: 3000 } }),
    new Paragraph({
      children: [new TextRun({ text: projectName, bold: true, size: 56, font: 'Calibri' })],
      alignment: AlignmentType.CENTER,
    }),
    new Paragraph({
      children: [new TextRun({ text: 'Claude Code Session Log', size: 32, color: '555555', font: 'Calibri' })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 600 },
    }),
    new Paragraph({
      children: [new TextRun({ text: `Generated by claude-stitch on ${formatDate(new Date())}`, size: 22, color: '888888' })],
      alignment: AlignmentType.CENTER,
    }),
    new Paragraph({
      children: [new TextRun({
        text: `${analytics.sessionCount} sessions | ${analytics.messageCount} messages | ${formatTokens(analytics.tokens.total)} tokens | ${formatCost(analytics.cost)}`,
        size: 22, color: '888888',
      })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 200 },
    }),
    new Paragraph({
      children: [new TextRun({
        text: `Date Range: ${formatDate(analytics.timeRange.start)} to ${formatDate(analytics.timeRange.end)}`,
        size: 20, color: 'AAAAAA',
      })],
      alignment: AlignmentType.CENTER,
    }),
    new Paragraph({ children: [new PageBreak()] }),
  );

  // ── Overview ───────────────────────────────────────────────
  children.push(
    new Paragraph({ text: 'Overview', heading: HeadingLevel.HEADING_1, spacing: { after: 200 } }),
  );

  children.push(createStatsTable([
    ['Sessions',        String(analytics.sessionCount)],
    ['Total Messages',  `${analytics.messageCount} (${analytics.userMessageCount} user, ${analytics.assistantMessageCount} assistant)`],
    ['Duration',        formatDuration(analytics.duration)],
    ['Date Range',      `${formatDate(analytics.timeRange.start)} to ${formatDate(analytics.timeRange.end)}`],
    ['Input Tokens',    `${formatTokens(analytics.tokens.input)} (${analytics.tokens.input.toLocaleString()})`],
    ['Output Tokens',   `${formatTokens(analytics.tokens.output)} (${analytics.tokens.output.toLocaleString()})`],
    ['Cache Write',     `${formatTokens(analytics.tokens.cacheWrite)} (${analytics.tokens.cacheWrite.toLocaleString()})`],
    ['Cache Read',      `${formatTokens(analytics.tokens.cacheRead)} (${analytics.tokens.cacheRead.toLocaleString()})`],
    ['Total Tokens',    `${formatTokens(analytics.tokens.total)} (${analytics.tokens.total.toLocaleString()})`],
    ['Estimated Cost',  formatCost(analytics.cost)],
    ['Models',          analytics.models.join(', ') || 'Unknown'],
  ]));
  children.push(new Paragraph({ spacing: { after: 200 } }));

  // ── AI Summary ─────────────────────────────────────────────
  if (options.summary) {
    children.push(
      new Paragraph({ text: 'Summary', heading: HeadingLevel.HEADING_1, spacing: { after: 200 } }),
    );
    for (const line of options.summary.split('\n')) {
      children.push(
        new Paragraph({
          children: [new TextRun({ text: line, size: 22 })],
          spacing: { after: 80 },
        }),
      );
    }
    children.push(new Paragraph({ spacing: { after: 200 } }));
  }

  // ── Files Modified ─────────────────────────────────────────
  if (analytics.topFiles.length > 0) {
    children.push(
      new Paragraph({ text: 'Files Modified', heading: HeadingLevel.HEADING_1, spacing: { before: 300, after: 200 } }),
    );
    children.push(createStatsTable(
      analytics.topFiles.map(f => [f.path, `${f.count} edits`]),
    ));
    children.push(new Paragraph({ spacing: { after: 200 } }));
  }

  // ── Table of Contents ──────────────────────────────────────
  children.push(
    new Paragraph({ text: 'Sessions', heading: HeadingLevel.HEADING_1, spacing: { before: 300, after: 200 } }),
  );
  for (let i = 0; i < sessions.length; i++) {
    const s = sessions[i];
    const models = s.models.length > 0 ? ` [${s.models.map(shortModel).join(', ')}]` : '';
    children.push(
      new Paragraph({
        children: [new TextRun({
          text: `${i + 1}. Session ${i + 1} -- ${formatDate(s.startTime)}${models} (${s.records.length} messages)`,
          size: 22,
        })],
        spacing: { after: 60 },
      }),
    );
  }

  children.push(new Paragraph({ children: [new PageBreak()] }));

  // ── Session Content ────────────────────────────────────────
  for (let i = 0; i < sessions.length; i++) {
    const session = sessions[i];
    let turnNumber = 0;

    children.push(
      new Paragraph({
        text: `Session ${i + 1} -- ${formatDate(session.startTime)}`,
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 400, after: 100 },
      }),
    );

    // Session metadata
    const metaParts = [];
    if (session.models.length > 0) metaParts.push(`Model: ${session.models.join(', ')}`);
    metaParts.push(`Started: ${formatDate(session.startTime)}`);
    metaParts.push(`Ended: ${formatDate(session.endTime)}`);
    metaParts.push(`Session ID: ${session.sessionId}`);

    children.push(
      new Paragraph({
        children: [new TextRun({ text: metaParts.join('  |  '), italics: true, size: 18, color: '888888' })],
        spacing: { after: 200 },
      }),
    );

    for (const record of session.records) {
      if (record.type === 'user') {
        turnNumber++;
        children.push(
          new Paragraph({
            children: [
              new TextRun({ text: `Turn ${turnNumber} -- User`, bold: true, size: 24, color: '2D5F2D' }),
              ...(record.timestamp ? [new TextRun({ text: `  ${formatDate(record.timestamp)}`, size: 18, color: 'AAAAAA' })] : []),
            ],
            heading: HeadingLevel.HEADING_2,
            spacing: { before: 300, after: 100 },
          }),
        );
        for (const line of (record.content || '').split('\n')) {
          children.push(
            new Paragraph({
              children: [new TextRun({ text: line, size: 22 })],
              spacing: { after: 60 },
            }),
          );
        }
      } else if (record.type === 'assistant') {
        turnNumber++;
        children.push(
          new Paragraph({
            children: [
              new TextRun({ text: `Turn ${turnNumber} -- Assistant`, bold: true, size: 24, color: '2D3F6F' }),
              ...(record.timestamp ? [new TextRun({ text: `  ${formatDate(record.timestamp)}`, size: 18, color: 'AAAAAA' })] : []),
            ],
            heading: HeadingLevel.HEADING_2,
            spacing: { before: 300, after: 100 },
          }),
        );

        // Assistant text
        if (record.content) {
          for (const line of record.content.split('\n')) {
            children.push(
              new Paragraph({
                children: [new TextRun({ text: line, size: 22 })],
                indent: { left: 360 },
                spacing: { after: 60 },
              }),
            );
          }
        }

        // Tool calls
        if (record.toolCalls && record.toolCalls.length > 0) {
          children.push(
            new Paragraph({
              children: [new TextRun({ text: 'Tool Calls:', bold: true, size: 20, color: '444444' })],
              spacing: { before: 120, after: 60 },
              indent: { left: 360 },
            }),
          );

          for (const tc of record.toolCalls) {
            children.push(
              new Paragraph({
                children: [new TextRun({ text: `[${tc.name}]`, bold: true, size: 20, color: '0055AA' })],
                spacing: { before: 80, after: 40 },
                indent: { left: 540 },
              }),
            );
            const inputStr = typeof tc.input === 'string' ? tc.input : JSON.stringify(tc.input, null, 2);
            for (const codeLine of inputStr.split('\n')) {
              children.push(
                new Paragraph({
                  children: [new TextRun({ text: codeLine, font: 'Courier New', size: 16 })],
                  shading: { type: ShadingType.SOLID, color: 'F2F2F2' },
                  indent: { left: 720 },
                  spacing: { after: 15 },
                }),
              );
            }
          }
        }

        // Usage
        if (record.usage) {
          const u = record.usage;
          const parts = [];
          if (u.input_tokens) parts.push(`Input: ${formatTokens(u.input_tokens)}`);
          if (u.output_tokens) parts.push(`Output: ${formatTokens(u.output_tokens)}`);
          if (u.cache_read_input_tokens) parts.push(`Cache: ${formatTokens(u.cache_read_input_tokens)}`);
          if (parts.length > 0) {
            children.push(
              new Paragraph({
                children: [new TextRun({ text: `Tokens: ${parts.join(' | ')}`, size: 18, color: 'AAAAAA', italics: true })],
                spacing: { before: 40, after: 80 },
                indent: { left: 360 },
              }),
            );
          }
        }
      }
    }

    // Page break between sessions (except last)
    if (i < sessions.length - 1) {
      children.push(new Paragraph({ children: [new PageBreak()] }));
    }
  }

  // ── Build & Write ──────────────────────────────────────────
  const doc = new Document({
    creator: 'claude-stitch',
    title: `${projectName} -- Claude Code Session Log`,
    description: `Session log with ${analytics.sessionCount} sessions, ${analytics.messageCount} messages, ${formatTokens(analytics.tokens.total)} tokens`,
    sections: [{ children }],
  });

  const buffer = await Packer.toBuffer(doc);
  await writeFile(outputPath, buffer);
}

// ── Helpers ──────────────────────────────────────────────────

function createStatsTable(rows) {
  const noBorder = { style: BorderStyle.NONE, size: 0 };
  const borders = { top: noBorder, bottom: noBorder, left: noBorder, right: noBorder };
  const thinBottom = { ...borders, bottom: { style: BorderStyle.SINGLE, size: 1, color: 'EEEEEE' } };

  return new Table({
    rows: rows.map(([label, value], idx) =>
      new TableRow({
        children: [
          new TableCell({
            children: [new Paragraph({ children: [new TextRun({ text: label, bold: true, size: 20, font: 'Calibri' })] })],
            width: { size: 25, type: WidthType.PERCENTAGE },
            borders: idx < rows.length - 1 ? thinBottom : borders,
          }),
          new TableCell({
            children: [new Paragraph({ children: [new TextRun({ text: value, size: 20, font: 'Calibri' })] })],
            width: { size: 75, type: WidthType.PERCENTAGE },
            borders: idx < rows.length - 1 ? thinBottom : borders,
          }),
        ],
      })
    ),
    width: { size: 100, type: WidthType.PERCENTAGE },
  });
}

function shortModel(modelId) {
  if (!modelId) return '?';
  if (modelId.includes('opus'))   return 'Opus';
  if (modelId.includes('sonnet')) return 'Sonnet';
  if (modelId.includes('haiku'))  return 'Haiku';
  return modelId;
}
