import { formatTokens, formatCost, formatDuration, formatDate } from '../utils/format.js';

/**
 * Export stitched sessions to a Markdown string.
 * Structured for AI readability: clear hierarchy, explicit labels, no ambiguous formatting.
 */
export function exportMarkdown(projectName, sessions, analytics, options = {}) {
  const lines = [];

  // ── Document Header ────────────────────────────────────────
  lines.push(`# ${projectName} -- Claude Code Session Log`);
  lines.push('');
  lines.push(`> Generated by **claude-stitch** on ${formatDate(new Date())}`);
  lines.push('');

  // ── Structured Metadata Block ──────────────────────────────
  lines.push('## Metadata');
  lines.push('');
  lines.push('```yaml');
  lines.push(`project: "${projectName}"`);
  lines.push(`generated: "${new Date().toISOString()}"`);
  lines.push(`sessions: ${analytics.sessionCount}`);
  lines.push(`messages: ${analytics.messageCount}`);
  lines.push(`user_messages: ${analytics.userMessageCount}`);
  lines.push(`assistant_messages: ${analytics.assistantMessageCount}`);
  lines.push(`duration: "${formatDuration(analytics.duration)}"`);
  lines.push(`date_range:`);
  lines.push(`  start: "${analytics.timeRange.start ? analytics.timeRange.start.toISOString() : 'unknown'}"`);
  lines.push(`  end: "${analytics.timeRange.end ? analytics.timeRange.end.toISOString() : 'unknown'}"`);
  lines.push(`tokens:`);
  lines.push(`  input: ${analytics.tokens.input}`);
  lines.push(`  output: ${analytics.tokens.output}`);
  lines.push(`  cache_write: ${analytics.tokens.cacheWrite}`);
  lines.push(`  cache_read: ${analytics.tokens.cacheRead}`);
  lines.push(`  total: ${analytics.tokens.total}`);
  lines.push(`estimated_cost_usd: ${analytics.cost.toFixed(4)}`);
  lines.push(`models: [${analytics.models.map(m => `"${m}"`).join(', ')}]`);
  lines.push('```');
  lines.push('');

  // ── Overview Table ─────────────────────────────────────────
  lines.push('## Overview');
  lines.push('');
  lines.push('| Metric | Value |');
  lines.push('|--------|-------|');
  lines.push(`| Sessions | ${analytics.sessionCount} |`);
  lines.push(`| Messages | ${analytics.messageCount} (${analytics.userMessageCount} user, ${analytics.assistantMessageCount} assistant) |`);
  lines.push(`| Duration | ${formatDuration(analytics.duration)} |`);
  lines.push(`| Date Range | ${formatDate(analytics.timeRange.start)} to ${formatDate(analytics.timeRange.end)} |`);
  lines.push(`| Total Tokens | ${formatTokens(analytics.tokens.total)} (${analytics.tokens.total.toLocaleString()}) |`);
  lines.push(`| Estimated Cost | ${formatCost(analytics.cost)} |`);
  lines.push(`| Models | ${analytics.models.join(', ') || 'Unknown'} |`);
  lines.push('');

  // ── AI Summary ─────────────────────────────────────────────
  if (options.summary) {
    lines.push('## Summary');
    lines.push('');
    lines.push(options.summary);
    lines.push('');
  }

  // ── Files Modified ─────────────────────────────────────────
  if (analytics.topFiles.length > 0) {
    lines.push('## Files Modified');
    lines.push('');
    lines.push('| File | Edit Count |');
    lines.push('|------|-----------|');
    for (const f of analytics.topFiles) {
      lines.push(`| \`${f.path}\` | ${f.count} |`);
    }
    lines.push('');
  }

  // ── Table of Contents ──────────────────────────────────────
  lines.push('## Table of Contents');
  lines.push('');
  for (let i = 0; i < sessions.length; i++) {
    const s = sessions[i];
    const anchor = `session-${i + 1}`;
    const models = s.models.length > 0 ? ` [${s.models.map(shortModel).join(', ')}]` : '';
    lines.push(`${i + 1}. [Session ${i + 1} -- ${formatDate(s.startTime)}${models}](#${anchor})`);
  }
  lines.push('');
  lines.push('---');
  lines.push('');

  // ── Session Content ────────────────────────────────────────
  for (let i = 0; i < sessions.length; i++) {
    const session = sessions[i];
    let turnNumber = 0;

    lines.push(`## Session ${i + 1}`);
    lines.push('');
    lines.push(`- **Started:** ${formatDate(session.startTime)}`);
    lines.push(`- **Ended:** ${formatDate(session.endTime)}`);
    if (session.models.length > 0) {
      lines.push(`- **Model:** ${session.models.join(', ')}`);
    }
    lines.push(`- **Session ID:** \`${session.sessionId}\``);
    lines.push('');

    for (const record of session.records) {
      if (record.type === 'user') {
        turnNumber++;
        lines.push(`### Turn ${turnNumber} -- User`);
        if (record.timestamp) {
          lines.push(`*${formatDate(record.timestamp)}*`);
        }
        lines.push('');
        lines.push(record.content || '*[empty message]*');
        lines.push('');
      } else if (record.type === 'assistant') {
        turnNumber++;
        lines.push(`### Turn ${turnNumber} -- Assistant`);
        if (record.timestamp) {
          lines.push(`*${formatDate(record.timestamp)}*`);
        }
        lines.push('');

        if (record.content) {
          lines.push(record.content);
          lines.push('');
        }

        if (record.toolCalls && record.toolCalls.length > 0) {
          lines.push('**Tool Calls:**');
          lines.push('');
          for (const tc of record.toolCalls) {
            lines.push(`- **${tc.name}**`);
            const inputStr = typeof tc.input === 'string' ? tc.input : JSON.stringify(tc.input, null, 2);
            if (inputStr && inputStr !== '{}' && inputStr !== 'null') {
              lines.push('');
              lines.push('  ```json');
              for (const codeLine of inputStr.split('\n')) {
                lines.push(`  ${codeLine}`);
              }
              lines.push('  ```');
            }
            lines.push('');
          }
        }

        if (record.usage) {
          const u = record.usage;
          const parts = [];
          if (u.input_tokens) parts.push(`in:${formatTokens(u.input_tokens)}`);
          if (u.output_tokens) parts.push(`out:${formatTokens(u.output_tokens)}`);
          if (u.cache_read_input_tokens) parts.push(`cache:${formatTokens(u.cache_read_input_tokens)}`);
          if (parts.length > 0) {
            lines.push(`*Tokens: ${parts.join(' | ')}*`);
            lines.push('');
          }
        }
      }
    }

    lines.push('---');
    lines.push('');
  }

  // ── Footer ─────────────────────────────────────────────────
  lines.push('*End of session log.*');
  lines.push('');

  return lines.join('\n');
}

function shortModel(modelId) {
  if (!modelId) return '?';
  if (modelId.includes('opus'))   return 'Opus';
  if (modelId.includes('sonnet')) return 'Sonnet';
  if (modelId.includes('haiku'))  return 'Haiku';
  return modelId;
}
