import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';
import { writeFile } from 'fs/promises';
import { formatTokens, formatCost, formatDuration, formatDate } from '../utils/format.js';

const PAGE_WIDTH = 595.28;  // A4
const PAGE_HEIGHT = 841.89;
const MARGIN = 50;
const LINE_HEIGHT = 15;
const CONTENT_WIDTH = PAGE_WIDTH - 2 * MARGIN;

// WinAnsi-safe replacement map
const CHAR_REPLACEMENTS = {
  '\u2192': '->', '\u2190': '<-', '\u2194': '<->',
  '\u2013': '-', '\u2014': '--', '\u2026': '...',
  '\u201c': '"', '\u201d': '"', '\u2018': "'", '\u2019': "'",
  '\u2022': '*', '\u2023': '>', '\u25cf': '*',
};

function sanitizeForPdf(text) {
  if (!text) return '';
  let result = text;
  for (const [char, replacement] of Object.entries(CHAR_REPLACEMENTS)) {
    result = result.replaceAll(char, replacement);
  }
  // Remove control characters (except newline/tab)
  result = result.replace(/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/g, '');
  // Remove non-WinAnsi (keep printable ASCII + Latin-1 supplement)
  result = result.replace(/[^\x09\x0A\x0D\x20-\xFF]/g, '');
  return result;
}

/**
 * Export stitched sessions to a PDF file.
 * Structured for AI readability: clear headings, turn numbering, timestamps.
 */
export async function exportPdf(outputPath, projectName, sessions, analytics, options = {}) {
  const doc = await PDFDocument.create();
  const helvetica = await doc.embedFont(StandardFonts.Helvetica);
  const helveticaBold = await doc.embedFont(StandardFonts.HelveticaBold);
  const helveticaOblique = await doc.embedFont(StandardFonts.HelveticaOblique);
  const courier = await doc.embedFont(StandardFonts.Courier);

  let page = null;
  let y = 0;
  let pageNum = 0;

  function newPage() {
    page = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
    y = PAGE_HEIGHT - MARGIN;
    pageNum++;
    // Page number footer
    page.drawText(`Page ${pageNum}`, {
      x: PAGE_WIDTH - MARGIN - 40, y: 25,
      size: 8, font: helvetica, color: rgb(0.7, 0.7, 0.7),
    });
  }

  function ensureSpace(needed = LINE_HEIGHT * 3) {
    if (!page || y < MARGIN + needed) newPage();
  }

  function drawText(text, { font = helvetica, size = 10, color = rgb(0, 0, 0), indent = 0, maxWidth = CONTENT_WIDTH } = {}) {
    const safeText = sanitizeForPdf(text);
    const lines = wrapText(safeText, font, size, maxWidth - indent);
    for (const line of lines) {
      ensureSpace(LINE_HEIGHT);
      page.drawText(line, { x: MARGIN + indent, y, size, font, color });
      y -= LINE_HEIGHT;
    }
  }

  function drawHeading(text, level = 1) {
    const configs = {
      1: { size: 18, spacing: 20, color: rgb(0.1, 0.1, 0.1) },
      2: { size: 14, spacing: 14, color: rgb(0.2, 0.2, 0.2) },
      3: { size: 11, spacing: 8, color: rgb(0.25, 0.25, 0.35) },
    };
    const cfg = configs[level] || configs[3];
    y -= cfg.spacing;
    ensureSpace(LINE_HEIGHT * 3);
    drawText(sanitizeForPdf(text), { font: helveticaBold, size: cfg.size, color: cfg.color });
    y -= 4;
  }

  function drawLine() {
    ensureSpace();
    page.drawLine({
      start: { x: MARGIN, y }, end: { x: PAGE_WIDTH - MARGIN, y },
      thickness: 0.5, color: rgb(0.85, 0.85, 0.85),
    });
    y -= LINE_HEIGHT;
  }

  function drawMeta(text) {
    drawText(text, { font: helveticaOblique, size: 8, color: rgb(0.55, 0.55, 0.55) });
  }

  // ── Cover Page ─────────────────────────────────────────────
  newPage();
  y = PAGE_HEIGHT - 220;
  drawText(sanitizeForPdf(projectName), { font: helveticaBold, size: 26 });
  y -= 8;
  drawText('Claude Code Session Log', { size: 16, color: rgb(0.4, 0.4, 0.4) });
  y -= 25;
  drawText(`Generated by cc-stitch on ${formatDate(new Date())}`, { size: 10, color: rgb(0.6, 0.6, 0.6) });
  y -= 5;
  drawText(`${analytics.sessionCount} sessions | ${analytics.messageCount} messages | ${formatTokens(analytics.tokens.total)} tokens | ${formatCost(analytics.cost)}`, {
    size: 10, color: rgb(0.6, 0.6, 0.6),
  });
  drawText(`Date Range: ${formatDate(analytics.timeRange.start)} to ${formatDate(analytics.timeRange.end)}`, {
    size: 10, color: rgb(0.6, 0.6, 0.6),
  });

  // ── Overview ───────────────────────────────────────────────
  newPage();
  drawHeading('Overview');

  const stats = [
    ['Sessions',       String(analytics.sessionCount)],
    ['Messages',       `${analytics.messageCount} (${analytics.userMessageCount} user, ${analytics.assistantMessageCount} assistant)`],
    ['Duration',       formatDuration(analytics.duration)],
    ['Date Range',     `${formatDate(analytics.timeRange.start)} to ${formatDate(analytics.timeRange.end)}`],
    ['Input Tokens',   `${formatTokens(analytics.tokens.input)} (${analytics.tokens.input.toLocaleString()})`],
    ['Output Tokens',  `${formatTokens(analytics.tokens.output)} (${analytics.tokens.output.toLocaleString()})`],
    ['Total Tokens',   `${formatTokens(analytics.tokens.total)} (${analytics.tokens.total.toLocaleString()})`],
    ['Estimated Cost', formatCost(analytics.cost)],
    ['Models',         analytics.models.join(', ') || 'Unknown'],
  ];
  for (const [label, value] of stats) {
    drawText(`${label}: ${value}`, { indent: 10, size: 10 });
  }

  // AI summary
  if (options.summary) {
    y -= 10;
    drawHeading('Summary');
    drawText(sanitizeForPdf(options.summary), { indent: 10 });
  }

  // Top files
  if (analytics.topFiles.length > 0) {
    y -= 10;
    drawHeading('Files Modified');
    for (const f of analytics.topFiles.slice(0, 20)) {
      drawText(`${f.path} (${f.count} edits)`, { font: courier, size: 8, indent: 10 });
    }
  }

  // ── Session Content ────────────────────────────────────────
  for (let i = 0; i < sessions.length; i++) {
    const session = sessions[i];
    let turnNumber = 0;

    newPage();
    drawHeading(`Session ${i + 1} -- ${formatDate(session.startTime)}`);

    const metaParts = [];
    if (session.models.length > 0) metaParts.push(`Model: ${session.models.join(', ')}`);
    metaParts.push(`Started: ${formatDate(session.startTime)}`);
    metaParts.push(`Ended: ${formatDate(session.endTime)}`);
    if (metaParts.length > 0) {
      drawMeta(metaParts.join('  |  '));
    }
    y -= 5;

    for (const record of session.records) {
      if (record.type === 'user') {
        turnNumber++;
        y -= 6;
        const ts = record.timestamp ? `  ${formatDate(record.timestamp)}` : '';
        drawHeading(`Turn ${turnNumber} -- User${ts}`, 2);
        drawText(sanitizeForPdf(record.content || '[empty]'), { indent: 10 });
      } else if (record.type === 'assistant') {
        turnNumber++;
        y -= 6;
        const ts = record.timestamp ? `  ${formatDate(record.timestamp)}` : '';
        drawHeading(`Turn ${turnNumber} -- Assistant${ts}`, 2);

        if (record.content) {
          drawText(sanitizeForPdf(record.content), { indent: 10 });
        }

        if (record.toolCalls && record.toolCalls.length > 0) {
          y -= 3;
          drawText('Tool Calls:', { font: helveticaBold, size: 9, indent: 10, color: rgb(0.3, 0.3, 0.5) });
          for (const tc of record.toolCalls) {
            drawText(`[${tc.name}]`, { font: helveticaBold, size: 9, indent: 15, color: rgb(0, 0.3, 0.7) });
            const inputStr = typeof tc.input === 'string' ? tc.input : JSON.stringify(tc.input, null, 2);
            for (const codeLine of sanitizeForPdf(inputStr).split('\n')) {
              drawText(codeLine, { font: courier, size: 7, indent: 20, color: rgb(0.35, 0.35, 0.35) });
            }
          }
        }

        // Token usage
        if (record.usage) {
          const u = record.usage;
          const parts = [];
          if (u.input_tokens) parts.push(`In: ${formatTokens(u.input_tokens)}`);
          if (u.output_tokens) parts.push(`Out: ${formatTokens(u.output_tokens)}`);
          if (parts.length > 0) {
            drawMeta(`Tokens: ${parts.join(' | ')}`);
          }
        }
      }
    }
  }

  const pdfBytes = await doc.save();
  await writeFile(outputPath, pdfBytes);
}

/**
 * Word-wrap text within a max width.
 */
function wrapText(text, font, fontSize, maxWidth) {
  if (!text) return [''];
  const result = [];
  for (const paragraph of text.split('\n')) {
    if (!paragraph.trim()) {
      result.push('');
      continue;
    }
    const words = paragraph.split(/\s+/);
    let line = '';
    for (const word of words) {
      const test = line ? `${line} ${word}` : word;
      let testWidth;
      try {
        testWidth = font.widthOfTextAtSize(test, fontSize);
      } catch {
        testWidth = test.length * fontSize * 0.5;
      }
      if (testWidth > maxWidth && line) {
        result.push(line);
        line = word;
      } else {
        line = test;
      }
    }
    if (line) result.push(line);
  }
  return result.length > 0 ? result : [''];
}
